### ISSUE TITLE
Per user settings request

### ISSUE THREAD

**Issue by zombiemooose** [patschi/factorio-transparent-inventory#1]
Is it possible to stop individual users from interacting with inventories in the admin settings?

**Comment by patschi** [comment]
You mean something like I've added in commit 7379af2047357a17461d75ad48585a2cceaf756e just right now? :)

**Comment by zombiemooose** [comment]
Haha brilliant. Well that's all I've got then!

**Comment by patschi** [comment]
I've just published it on Factorio Mods as well :) So far I've done quite intensive testing and everything appears working as expected. If something doesn't behave correctly, please just let me know!
